apiVersion: v1
kind: ConfigMap
metadata:
  name: user-mssql-initdb
data:
  init.sql: |
    USE master;
    GO
    IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'usersdb')
    BEGIN
        CREATE DATABASE usersdb;
    END
