apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-mssql-initdb
data:
  init.sql: |
    USE master;
    GO
    IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'garagesdb')
    BEGIN
        CREATE DATABASE garagesdb;
    END
