apiVersion: v1
kind: ConfigMap
metadata:
  name: car-mssql-initdb
data:
  init.sql: |
    USE master;
    GOk
    IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'carsdb')
    BEGIN
        CREATE DATABASE carsdb;
    END
