apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-mssql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-mssql
  template:
    metadata:
      labels:
        app: car-mssql
    spec:
      containers:
        - name: car-mssql
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Express"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: car-mssql
                  key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: car-mssqldb
            - mountPath: /docker-entrypoint-initdb.d
              name: car-mssql-initdb
              readOnly: true
      volumes:
        - name: car-mssqldb
          persistentVolumeClaim:
            claimName: car-mssql-claim
        - name: car-mssql-initdb
          configMap:
            name: car-mssql-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: cars-mssql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: car-mssql
  ports:
    - name: car-mssql
      protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: cars-mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: car-mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
