apiVersion: apps/v1
kind: Deployment
metadata:
  name: environments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: environmentservice
  template:
    metadata:
      labels:
        app: environmentservice
    spec:
      containers:
        - name: environmentservice
          image: jecksparr0w/environmentservice:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: environments-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: environmentservice
  ports:
    - name: environmentservice
      protocol: TCP
      port: 80
      targetPort: 80
