on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "CarService/**"
  pull_request:
    branches:
      - main
    paths:
      - "CarService/**"

  lint:
    defaults:
      run:
        working-directory: ./CarService
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Cache dotnet format
        id: cache-dotnet-format
        uses: actions/cache@v3
        with:
          path: ~/.dotnet/tools
          key: ${{ runner.os }}-dotnet-format-${{ hashFiles('**/CarService.csproj') }}
      - name: Install dotnet format
        if: steps.cache-dotnet-format.outputs.cache-hit != 'true'
        run: dotnet tool install -g dotnet-format
        - name: Format code
          id: format
          run: dotnet format --verbosity diagnostic
        - name: Commit files 
          if: steps.format.outputs.has-changes == 'true'
          run: |
            git branch lint-updates
            git checkout lint-updates
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git commit -a -m 'Automated dotnet-format update'
            git push origin lint-updates

