# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CarService.NET CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'CarService/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'CarService/**'
      
jobs:
  build:
    defaults:
      run:
        working-directory: ./CarService
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/CarService.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

  lint:
    needs: build
    defaults:
      run:
        working-directory: ./CarService
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Cache dotnet format
        id: cache-dotnet-format
        uses: actions/cache@v2
        with:
          path: ~/.dotnet/tools
          key: ${{ runner.os }}-dotnet-format-${{ hashFiles('**/CarService.csproj') }}
      - name: Install dotnet format
        if: steps.cache-dotnet-format.outputs.cache-hit != 'true'
        run: dotnet tool install -g dotnet-format
      - name: Format code
        run: dotnet format --check --verbosity normal

  test:
    needs: build
    defaults:
      run:
        working-directory: ./CarService
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Test
        run: dotnet test --no-build --verbosity normal
