# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CarService.NET CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'CarService/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'CarService/**'
      
jobs:
  build:
    defaults:
      run:
        working-directory: ./CarService
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache dependencies
        id: cache-dependecies
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/CarService.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-
            
      - name: Cache dotnet
        id: cache-dotnet
        uses: actions/cache@v2
        with:
          path: ./.dotnet
          key: ${{ runner.os }}-dotnet-6
          restore-keys: ${{ runner.os }}-dotnet-6
          
      - name: Setup .NET
        if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        if: ${{ steps.cache-dependecies.outputs.cache-hit != 'true' }}
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
  
  test:
    needs: build
    defaults:
      run:
        working-directory: ./CarService
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache dotnet
        id: cache-dotnet
        uses: actions/cache@v2
        with:
          path: ./.dotnet
          key: ${{ runner.os }}-dotnet-6
          restore-keys: ${{ runner.os }}-dotnet-6
          
      - name: Setup .NET
        if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Test
        run: dotnet test --no-build --verbosity normal
