name: UserService.NET CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "UserService/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "UserService/**"

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./UserService
          file: ./UserService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/userservice:latest



